require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7

  DisplayCopNames:
    Enabled: true

  DisplayStyleGuide:
    Enabled: true

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Layout/LineLength:
  Max: 180
