---
dist: xenial
language: ruby
before_install:
  - sudo add-apt-repository --yes ppa:wireguard/wireguard
  - sudo apt-get --yes update
  - sudo apt-get --yes install wireguard
rvm:
- 2.7.1
- 2.6.6
- 2.5.8
