---
dist: xenial
language: ruby
before_install:
  - sudo add-apt-repository --yes ppa:wireguard/wireguard
  - sudo apt-get --yes update
  - sudo apt-get --yes install wireguard
rvm:
- 2.6.8
- 2.7.4
- 3.0.2
